# In _config.yml
title: Reinforcement learning - advanced topics practical hands-on
author: Sergey V. Kovalchuk, Ashish T.S. Ireddy, Chao Li, Ekaterina Kravtsova
# logo: logo.png
execute:
  execute_notebooks: 'off'

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib